### ISSUE TITLE
Read HTTP/HTTPS Support

### ISSUE THREAD

**Issue by abresler** [hrbrmstr/docxtractr#1]
Fantastic package, would be great to add the ability to read doc and docx directly from the web like how it works in read_csv in readr.  If I get sometime today I will look at that code and see how they ado it there

**Comment by hrbrmstr** [comment]
you would want this now wouldn't you 😜 I shall add said code. it's a pretty simple add.

**Comment by abresler** [comment]
Sure why not!  Think it will be a great feature; so much table data on the web in world files!

**Comment by hrbrmstr** [comment]
really? I was having a hard time finding some, though my work doesn't really involve dealing with tablular word files.

**Comment by hrbrmstr** [comment]
That was more of a test to see if that whole "Closes #issuenumber" text in a commit actually worked. give it a go!
