### ISSUE TITLE
CRAN Submission

### ISSUE THREAD

**Issue by muschellij2** [hrbrmstr/docxtractr#28]
Do you have a timeline for submitting to CRAN.  Trying to rely on the `convert_to_pdf` function for PPTX for a package, so I have a requirement on `docxtractr` version that works, but that's only on GitHub.  So I sent #27 to try to get it rolling.

Rhub checking: https://builder.r-hub.io/status/docxtractr_0.6.2.tar.gz-2796c8bc1a0e4bf2873c7e1673ad4834

**Comment by muschellij2** [comment]
Error in `rhub` due to:
https://github.com/r-hub/rhub/issues/367#issuecomment-621757715 (aka it's an `rhub` issue not the package)

**Comment by muschellij2** [comment]
https://builder.r-hub.io/status/docxtractr_0.6.2.tar.gz-05819c7a7b9345859a53deff3e41749d

**Comment by hrbrmstr** [comment]
on it's way to mirrors! #ty!
