### ISSUE TITLE
Text outside of tables

### ISSUE THREAD

**Issue by slarge** [hrbrmstr/docxtractr#6]
I know the impetus of this package is to read data from .docx tables, but I am wondering if the xml structure would permit pulling text from beneath a specific heading. In a .docx with a common format, for example:

# Introduction
Chicken ullamco meatball, magna tail elit meatloaf aliquip jerky cillum. Id chicken ut, meatloaf dolore jowl cupim porchetta aliqua tempor tenderloin sausage quis aute. Et deserunt est ground round, chicken ea do ball tip laboris tri-tip ullamco id occaecat chuck. Brisket cupim meatloaf veniam porchetta picanha meatball quis flank t-bone elit dolor rump.

# Materials and Methods
Bacon ipsum dolor amet bacon dolore commodo id. Est veniam nostrud hamburger eu meatball nisi ut. Ham hock adipisicing anim aliqua ullamco. In ad cow flank meatball. Ut ham laboris incididunt pancetta do venison dolor fatback. Sint alcatra incididunt, shank sunt ground round commodo meatball tail filet mignon.

something like: 
docx_extract_txt(doc, heading = "Introduction")
> "Chicken ullamco meatball, magna ..."

returning a string of text. Not sure if this would be possible, but I think it could be extremely useful. 
EDIT: I replaced "header" with "heading", as that seems to be more precise usage of what I'm after in MS Word parlance.

**Comment by hrbrmstr** [comment]
Can you attach a (small-ish) docx file? This sounds like a fairly reasonable request (potentially useful for NLP or text extraction for reporting).

**Comment by slarge** [comment]
[txthdr.docx](https://github.com/hrbrmstr/docxtractr/files/581771/txthdr.docx)

is a .docx version of the simple example mentioned above. If you want something that is a bit more crazy, let me know and I'll send you something else. Thanks in advance for your insight, I'm excited to learn more about how .docx structure can be utilized!

**Comment by slarge** [comment]
I think that @davidgohel has mostly addressed this issue within `officer` package (although I haven't tested the office scraping functionality, yet).

https://davidgohel.github.io/officer/articles/officer_reader.html

Thank you @hrbrmstr and @davidgohel for creating and maintaining such useful tools that enable R users to slip some logic into the .docx ecosystems many organizations are locked into.

**Comment by hrbrmstr** [comment]
#ty and aye, `officer` is an extremely well-designed and well-executed pkg (I have to do more generation than extraction but either way it's superb).

**Comment by davidgohel** [comment]
@hrbrmstr you're too kind and modest!
