### ISSUE TITLE
Possible to have output as tibble?

### ISSUE THREAD

**Issue by benmarwick** [hrbrmstr/docxtractr#7]
This is an awesome pkg, and I find `assign_colnames` useful for all kinds of data input besides docx files. 

I wonder if you would consider allowing the tables output by `docx_extract_tbl()` to be tibbles?  For a new data set coming in to my R environment I find it very handy to see the column classes that the tibble print method gives. 

Could we change [this line](https://github.com/hrbrmstr/docxtractr/blob/master/R/docx_find_tbls.r#L51) to `as_tibble(dat)` ? 

You have tibble in suggests already, so I don't think this will change the dependencies. Just thought I'd ask before making at PR in case you have a good reason not to do this.

**Comment by hrbrmstr** [comment]
in fact, i was quite daft with `assign_colnames()` as it clobbered input data frame class as well. Things that "shld" return tibbles return tibbles, now and I added some other bits of cleanup I had failed to push earlier. #ty for the suggestion!

**Comment by benmarwick** [comment]
Thanks very much! I love the new `mcga()`! (worth a mention in the [NEWS](https://github.com/hrbrmstr/docxtractr/commit/7829003217382327d11e303292823d0bc18e6529#diff-8312ad0561ef661716b48d09478362f3R1), too, no?). It inspired me to push this little add-in out to GitHub: https://github.com/benmarwick/snakecaser
