### ISSUE TITLE
can't read from a local file

### ISSUE THREAD

**Issue by kimjj93** [hrbrmstr/docxtractr#8]
Hello,

Thanks for the great package.  I'm having issues reading a doc file from my workspace.
For example,

doc1 <- read_docx("myfile.docx")

This simple code doesn't work.  I get -
Error: 'C:\Users\smithj\AppData\Local\Temp\1\RtmpqqbQyW/docdata/word/document.xml' does not exist.

I can read in from the examples like:
complx <- read_docx(system.file("examples/complex.docx", package="docxtractr"))

I don't want to copy all my files to the package example directories.  Maybe I'm doing something wrong??  I tried to google but haven't had a success.

Thanks,

**Comment by hrbrmstr** [comment]
Thx for both trying out the pkg and for taking the time to file a bug report!

I might have an idea and may try to get a test fix out for this by tomorrow or at least something which can provide more useful error messages.

**Comment by kimjj93** [comment]
Hello,

I found what's wrong with this.  The word version I was trying to use was an old version (Word 97-2003 - doc) - after converting it into the docx version, it works fine.

Thanks for your quick response!
