### ISSUE TITLE
Is there a way to conserve newlines from extracted tables?

### ISSUE THREAD

**Issue by gnawhnehpets** [hrbrmstr/docxtractr#9]
I have a word doc with tables containing cells with newlines. When I extract the cell, all newlines appear to be simply deleted. Any way to keep the formatting?

**Comment by hrbrmstr** [comment]
Thx for checking out the pkg and taking time to file an issue!

Can you post a small word doc that has the content this way (so I can add it to the test suite once I'm done modifying the code).

I'm 99% sure I can add a parameter that will keep formatting.

**Comment by gnawhnehpets** [comment]
I appreciate the quick response. Would it be difficult to keep font formatting (bold, italics, etc.)?

[test.docx](https://github.com/hrbrmstr/docxtractr/files/1334504/test.docx)

**Comment by hrbrmstr** [comment]
I threw together a quick "fix" to see if it's enough. Do a gh install of the pkg and try the following ("preserve.docx" is your test file which is _greatly_ appreciated!).

The new `preserve` parameter will preserve the paragraph in a cell (they'll be newlines in the character field in the data frame).

It'll take a bit more time to see what I can do abt tables-within-tables.

    library(docxtractr)

    intracell_whitespace <- read_docx(system.file("examples/preserve.docx", package="docxtractr"))

    docx_extract_all_tbls(intracell_whitespace, preserve=FALSE) # this is the default
    ## [[1]]
    ## # A tibble: 6 x 2
    ##   `Test1:`
    ##      <chr>
    ## 1   Test2:
    ## 2   Test3:
    ## 3   Test4:
    ## 4   Test5:
    ## 5   Test6:
    ## 6   Test7:
    ## # ... with 1 more variables: Apple <chr>
    ## 
    ## [[2]]
    ## # A tibble: 2 x 4
    ##      ``  Kite      Lemur Madagascar
    ##   <chr> <chr>      <chr>      <chr>
    ## 1 Nanny  Open       Port    Quarter
    ## 2  Rain  Sand Television    Unicorn
    ## 
    ## [[3]]
    ## # A tibble: 2 x 2
    ##   `Test8:`            XylophoneYew
    ##      <chr>                   <chr>
    ## 1   Test9:                   Zebra
    ## 2  Test10: Apple2Banana2Cranberry2

^^ is the default (no preserving). Below you'll see newlines.
    
    docx_extract_all_tbls(intracell_whitespace, preserve=TRUE)
    ## [[1]]
    ## # A tibble: 6 x 2
    ##   `Test1:`                                   Apple
    ##      <chr>                                   <chr>
    ## 1   Test2:                                  Banana
    ## 2   Test3:                       "Cranberry\nDark"
    ## 3   Test4:               "Elephant, Farm\nGrandpa"
    ## 4   Test5:                "Hat\nIgloo\nJackrabbit"
    ## 5   Test6: " \nQuestion1\n[ ] Underwear\n[ ] VM\n"
    ## 6   Test7:                                    Warm
    ## 
    ## [[2]]
    ## # A tibble: 2 x 4
    ##      ``  Kite      Lemur Madagascar
    ##   <chr> <chr>      <chr>      <chr>
    ## 1 Nanny  Open       Port    Quarter
    ## 2  Rain  Sand Television    Unicorn
    ## 
    ## [[3]]
    ## # A tibble: 2 x 2
    ##   `Test8:`              `Xylophone\nYew`
    ##      <chr>                         <chr>
    ## 1   Test9:                         Zebra
    ## 2  Test10: "Apple2\nBanana2\nCranberry2"

Give it a go and let me know what's busted or what cld use some tweaking.
